############################################################
# Dockerfile to build Tomcat container image
# Based on vm_tomcat1
############################################################

# Set the base image to vm_tomcat1
FROM vm_tomcat1

# File Author / Maintainer
MAINTAINER  groupe_phoenix
